export const JUDGE0_LANGUAGES = [
  {
    id: 45,
    name: "Assembly (NASM 2.14.02)",
    extension: "asm",
    monacoLang: "plaintext",
  },
  { id: 46, name: "Bash (5.0.0)", extension: "sh", monacoLang: "shell" },
  {
    id: 47,
    name: "Basic (FBC 1.07.1)",
    extension: "bas",
    monacoLang: "plaintext",
  },
  { id: 50, name: "C (GCC 9.2.0)", extension: "c", monacoLang: "c" },
  { id: 54, name: "C++ (GCC 9.2.0)", extension: "cpp", monacoLang: "cpp" },
  {
    id: 86,
    name: "Clojure (1.10.1)",
    extension: "clj",
    monacoLang: "clojure",
  },
  {
    id: 51,
    name: "C# (Mono 6.6.0.161)",
    extension: "cs",
    monacoLang: "csharp",
  },
  {
    id: 77,
    name: "COBOL (GnuCOBOL 2.2)",
    extension: "cob",
    monacoLang: "plaintext",
  },
  {
    id: 55,
    name: "Common Lisp (SBCL 2.0.0)",
    extension: "lisp",
    monacoLang: "plaintext",
  },
  {
    id: 56,
    name: "D (DMD 2.089.1)",
    extension: "d",
    monacoLang: "plaintext",
  },
  {
    id: 57,
    name: "Elixir (1.9.4)",
    extension: "ex",
    monacoLang: "plaintext",
  },
  {
    id: 58,
    name: "Erlang (OTP 22.2)",
    extension: "erl",
    monacoLang: "plaintext",
  },
  {
    id: 87,
    name: "F# (.NET Core SDK 3.1.202)",
    extension: "fs",
    monacoLang: "fsharp",
  },
  {
    id: 59,
    name: "Fortran (GFortran 9.2.0)",
    extension: "f90",
    monacoLang: "plaintext",
  },
  { id: 60, name: "Go (1.13.5)", extension: "go", monacoLang: "go" },
  {
    id: 88,
    name: "Groovy (3.0.3)",
    extension: "groovy",
    monacoLang: "plaintext",
  },
  {
    id: 61,
    name: "Haskell (GHC 8.8.1)",
    extension: "hs",
    monacoLang: "haskell",
  },
  {
    id: 62,
    name: "Java (OpenJDK 13.0.1)",
    extension: "java",
    monacoLang: "java",
  },
  {
    id: 63,
    name: "JavaScript (Node.js 12.14.0)",
    extension: "js",
    monacoLang: "javascript",
  },
  { id: 78, name: "Kotlin (1.3.70)", extension: "kt", monacoLang: "kotlin" },
  { id: 64, name: "Lua (5.3.5)", extension: "lua", monacoLang: "lua" },
  {
    id: 89,
    name: "Multi-file program",
    extension: "txt",
    monacoLang: "plaintext",
  },
  {
    id: 79,
    name: "Objective-C (Clang 7.0.1)",
    extension: "m",
    monacoLang: "objective-c",
  },
  {
    id: 65,
    name: "OCaml (4.09.0)",
    extension: "ml",
    monacoLang: "plaintext",
  },
  {
    id: 66,
    name: "Octave (5.1.0)",
    extension: "octave",
    monacoLang: "plaintext",
  },
  {
    id: 67,
    name: "Pascal (FPC 3.0.4)",
    extension: "pas",
    monacoLang: "pascal",
  },
  { id: 85, name: "Perl (5.28.1)", extension: "pl", monacoLang: "perl" },
  { id: 68, name: "PHP (7.4.1)", extension: "php", monacoLang: "php" },
  { id: 43, name: "Plain Text", extension: "txt", monacoLang: "plaintext" },
  {
    id: 69,
    name: "Prolog (GNU Prolog 1.4.5)",
    extension: "pro",
    monacoLang: "plaintext",
  },
  { id: 70, name: "Python (2.7.17)", extension: "py2", monacoLang: "python" },
  { id: 71, name: "Python (3.8.1)", extension: "py", monacoLang: "python" },
  { id: 80, name: "R (4.0.0)", extension: "r", monacoLang: "r" },
  { id: 72, name: "Ruby (2.7.0)", extension: "rb", monacoLang: "ruby" },
  { id: 73, name: "Rust (1.40.0)", extension: "rs", monacoLang: "rust" },
  { id: 81, name: "Scala (2.13.2)", extension: "scala", monacoLang: "scala" },
  {
    id: 82,
    name: "SQL (SQLite 3.27.2)",
    extension: "sql",
    monacoLang: "sql",
  },
  { id: 83, name: "Swift (5.2.3)", extension: "swift", monacoLang: "swift" },
  {
    id: 74,
    name: "TypeScript (3.7.4)",
    extension: "ts",
    monacoLang: "typescript",
  },
  {
    id: 84,
    name: "Visual Basic.Net (vbnc 0.0.0.5943)",
    extension: "vb",
    monacoLang: "vb",
  },
];
